//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyBanHangSieuThiFullEntities : DbContext
    {
        public QuanLyBanHangSieuThiFullEntities()
            : base("name=QuanLyBanHangSieuThiFullEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHITIETHOADON> CHITIETHOADONs { get; set; }
        public virtual DbSet<CHUCVU> CHUCVUs { get; set; }
        public virtual DbSet<DANGNHAP> DANGNHAPs { get; set; }
        public virtual DbSet<HOADON> HOADONs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<LOAISANPHAM> LOAISANPHAMs { get; set; }
        public virtual DbSet<NHACUNGCAP> NHACUNGCAPs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<PHONGBAN> PHONGBANs { get; set; }
        public virtual DbSet<SANPHAM> SANPHAMs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<vw_Hienthichitiethoadon> vw_Hienthichitiethoadon { get; set; }
        public virtual DbSet<vw_Hienthichitiethoadon2> vw_Hienthichitiethoadon2 { get; set; }
        public virtual DbSet<vw_Hienthihoadon> vw_Hienthihoadon { get; set; }
        public virtual DbSet<vw_Hienthikhachang> vw_Hienthikhachang { get; set; }
        public virtual DbSet<vw_Hienthinhanvien> vw_Hienthinhanvien { get; set; }
        public virtual DbSet<vw_Hienthinhanvien2> vw_Hienthinhanvien2 { get; set; }
        public virtual DbSet<vw_Hienthisanpham> vw_Hienthisanpham { get; set; }
        public virtual DbSet<vw_Hienthisanpham2> vw_Hienthisanpham2 { get; set; }
    }
}
