//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Hienthisanpham2
    {
        public int Masanpham { get; set; }
        public string Tensanpham { get; set; }
        public int Maloai { get; set; }
        public string Tenloai { get; set; }
        public string Tennhacungcap { get; set; }
        public Nullable<double> Gianhap { get; set; }
        public Nullable<double> Giaban { get; set; }
        public string Donvi { get; set; }
        public Nullable<int> Soluong { get; set; }
    }
}
