//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Hienthihoadon
    {
        public int Mahoadon { get; set; }
        public string Tenkhachhang { get; set; }
        public string Tennhanvien { get; set; }
        public Nullable<System.DateTime> Ngayban { get; set; }
    }
}
