//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Hienthinhanvien2
    {
        public int Manhanvien { get; set; }
        public string Tennhanvien { get; set; }
        public string Gioitinh { get; set; }
        public Nullable<System.DateTime> Ngaysinh { get; set; }
        public string Diachi { get; set; }
        public string Sodienthoai { get; set; }
        public int Maphongban { get; set; }
        public string Tenphongban { get; set; }
        public string Tenchucvu { get; set; }
    }
}
